spring:
  application:
    name: usage-service

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: usage-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: energyUsageEvent:com.enerlytics.EnergyUsageEvent
    default-topic: energy-alerts
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

influxdb:
  url: http://localhost:8072
  token: my-token
  org: enerlytics
  bucket: usage-bucket

device-service:
  base-url: http://localhost:8081/api/v1/devices

user-service:
  base-url: http://localhost:8080/api/v1/users

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    enable:
      http:
        client:
          requests: true
        server:
          requests: true

server:
  port: 8083
